#!/usr/bin/env bash
set -uo pipefail

# Foundation closure audit for Monad.
#
# This script intentionally does not stop at the first failure. The purpose of
# WP-E7-001 is to record the real current state, including blockers.

AUDIT_ROOT=".artifacts/audits/foundation-closure"
TIMESTAMP="$(date -u +"%Y%m%dT%H%M%SZ")"
RUN_DIR="$AUDIT_ROOT/$TIMESTAMP"
REPORT="docs/project/FOUNDATION-CLOSURE-AUDIT.md"

mkdir -p "$RUN_DIR" docs/project

command_index=0
SUMMARY_ROWS=""

record_command() {
  local name="$1"
  shift

  command_index=$((command_index + 1))

  local slug
  slug="$(printf "%02d-%s" "$command_index" "$name" | tr '[:upper:]' '[:lower:]' | tr ' /:' '---' | tr -cd 'a-z0-9._-')"

  local log_file="$RUN_DIR/$slug.log"
  local exit_file="$RUN_DIR/$slug.exit"

  echo
  echo "==> [$command_index] $name"
  echo "    command: $*"
  echo "    log: $log_file"

  {
    echo "\$ $*"
    echo
    "$@"
  } >"$log_file" 2>&1

  local status=$?
  echo "$status" >"$exit_file"

  if [[ "$status" -eq 0 ]]; then
    SUMMARY_ROWS="${SUMMARY_ROWS}| ${command_index} | ${name} | PASS | \`${log_file}\` |
"
    echo "    result: PASS"
  else
    SUMMARY_ROWS="${SUMMARY_ROWS}| ${command_index} | ${name} | FAIL (${status}) | \`${log_file}\` |
"
    echo "    result: FAIL ($status)"
  fi

  return 0
}

record_command "git status" git status --short
record_command "git log" git log --oneline --max-count=12

record_command "cargo fmt check" cargo fmt --check
record_command "cargo test" cargo test
record_command "cargo clippy" cargo clippy --all-targets --all-features -- -D warnings

record_command "cli help" cargo run -p monad-cli -- --help
record_command "cli version" cargo run -p monad-cli -- version
record_command "cli inspect" cargo run -p monad-cli -- inspect
record_command "cli check" cargo run -p monad-cli -- check
record_command "cli plan" cargo run -p monad-cli -- plan "explain this repository"
record_command "cli evolve verify baseline dry run" cargo run -p monad-cli -- evolve verify-baseline --dry-run
record_command "cli evolve context baseline dry run" cargo run -p monad-cli -- evolve context-baseline --dry-run

record_command "root verify script" tools/scripts/verify.sh

cat > "$REPORT" <<REPORT_EOF
---
title: Foundation Closure Audit
description: Verification audit for closing Monad foundation epics E0 through E6 and starting E7 MVP hardening.
status: draft
version: 0.1.0
created: 2026-05-28
updated: 2026-05-28
owner: Thomas Carter
project: Monad
phase: MVP Hardening
epic: E7
work_packet: WP-E7-001
audit_run_id: ${TIMESTAMP}
audit_artifact_dir: ${RUN_DIR}
---

# Foundation Closure Audit

## 1. Purpose

This audit records the actual local verification state of Monad after the E0–E6 foundation phase and at the start of E7 MVP hardening.

The goal is not to hide failures. The goal is to establish a factual baseline so the next hardening packets can fix real problems in priority order.

## 2. Audit run metadata

| Field | Value |
|---|---|
| Audit run ID | \`${TIMESTAMP}\` |
| Artifact directory | \`${RUN_DIR}\` |
| Work packet | WP-E7-001 — Run foundation closure audit |
| Epic | E7 — MVP Hardening |
| Generated by | \`tools/scripts/audit-foundation-closure.sh\` |

## 3. Command summary

| # | Check | Result | Log |
|---:|---|---|---|
${SUMMARY_ROWS}

## 4. Interpretation

Review the command summary above.

A result of **PASS** means the command exited with status code 0.

A result of **FAIL** means the command exited with a non-zero status code and must be reviewed in the referenced log file.

This audit does not automatically fix failures.

## 5. Required manual review

After generating this report, review:

1. failed command logs
2. CLI smoke-test output
3. dry-run output
4. whether any command unexpectedly changed \`git status --short\`
5. whether package names in docs match actual Cargo packages
6. whether \`tools/scripts/verify.sh\` still reflects the current project structure

## 6. Blockers discovered

Fill this section after reviewing logs.

- [ ] No blockers found.
- [ ] Blockers found and listed below.

### Blocker list

<!-- Add blocker bullets here. Example:
- \`cargo clippy\` fails because ...
- \`monad plan\` fails because ...
-->

## 7. Follow-up recommendations

Fill this section after reviewing logs.

Expected follow-up categories:

- CLI UX fixes for WP-E7-002
- smoke-test additions for WP-E7-003
- documentation corrections for WP-E7-004
- dry-run/no-write hardening for WP-E7-005
- readiness conclusions for WP-E7-006

## 8. Closure status

WP-E7-001 should be considered complete when:

- this audit file exists
- logs exist under \`${RUN_DIR}\`
- failures are reviewed
- blockers are listed or explicitly marked absent
- the audit is committed
REPORT_EOF

echo
echo "Foundation closure audit written to: $REPORT"
echo "Audit logs written to: $RUN_DIR"
