#!/usr/bin/env bash
set -euo pipefail

if git rev-parse --show-toplevel >/dev/null 2>&1; then
  REPO_ROOT="$(git rev-parse --show-toplevel)"
else
  REPO_ROOT="$(pwd)"
fi

cd "$REPO_ROOT"

VERSION="$(awk -F '"' '/^version[[:space:]]*=/ { print $2; exit }' Cargo.toml 2>/dev/null || true)"

if [ -z "$VERSION" ]; then
  VERSION="$(awk -F '"' '/^version[[:space:]]*=/ { print $2; exit }' crates/monad-cli/Cargo.toml 2>/dev/null || true)"
fi

if [ -z "$VERSION" ]; then
  echo "ERROR: could not detect release version from Cargo.toml" >&2
  exit 1
fi

BINARY="target/release/monad-cli"
if [ ! -f "$BINARY" ]; then
  echo "ERROR: release binary not found: $BINARY" >&2
  echo "Run: cargo build --release -p monad-cli" >&2
  exit 1
fi

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
RELEASE_DIR=".monad/releases/v${VERSION}"
STAGING_DIR="${RELEASE_DIR}/monad-${VERSION}-${OS}-${ARCH}"
ARCHIVE="${RELEASE_DIR}/monad-${VERSION}-${OS}-${ARCH}.tar.gz"
CHECKSUM="${ARCHIVE}.sha256"

mkdir -p "$STAGING_DIR"

cp "$BINARY" "$STAGING_DIR/monad"
chmod +x "$STAGING_DIR/monad"

cat > "$STAGING_DIR/README.txt" <<README
Monad ${VERSION}

This is a local release artifact generated by tools/scripts/package-release.sh.

This script does not publish packages, create GitHub releases, create tags, or upload artifacts.
README

tar -czf "$ARCHIVE" -C "$RELEASE_DIR" "$(basename "$STAGING_DIR")"

if command -v sha256sum >/dev/null 2>&1; then
  sha256sum "$ARCHIVE" > "$CHECKSUM"
elif command -v shasum >/dev/null 2>&1; then
  shasum -a 256 "$ARCHIVE" > "$CHECKSUM"
else
  echo "ERROR: neither sha256sum nor shasum is available" >&2
  exit 1
fi

echo "Release artifact written:"
echo "  archive:  $ARCHIVE"
echo "  checksum: $CHECKSUM"
echo
echo "No packages were published."
echo "No Git tags were created."
echo "No GitHub release was created."
