//! Markdown evidence report rendering for Monad verification.

use std::fs;
use std::path::PathBuf;

use crate::{
    CheckRunReport, EvidenceCommandSummary, EvidencePacket, MonadError, MonadResult,
    WorkspaceContext,
};

/// Default evidence report path relative to the workspace root.
pub const DEFAULT_EVIDENCE_REPORT_PATH: &str = ".monad/reports/latest-check-evidence.md";

/// Builds an evidence packet from a check run report.
#[must_use]
pub fn evidence_packet_from_check_run_report(report: &CheckRunReport) -> EvidencePacket {
    EvidencePacket::from_check_run_report(report)
}

/// Renders an evidence packet as reviewable Markdown.
#[must_use]
pub fn render_evidence_packet_markdown(packet: &EvidencePacket) -> String {
    let summary = packet.summary();
    let mut lines = Vec::new();

    lines.push(format!("# {}", packet.title()));
    lines.push(String::new());
    lines.push("## Metadata".to_string());
    lines.push(String::new());
    lines.push(format!("- Schema version: {}", packet.schema_version()));
    lines.push(format!("- Generated by: {}", packet.generated_by()));
    lines.push("- Generated timestamp: intentionally omitted for stable diffs".to_string());
    lines.push(String::new());

    lines.push("## Summary".to_string());
    lines.push(String::new());
    lines.push(format!(
        "- Result: {}",
        if summary.passed() { "passed" } else { "failed" }
    ));
    lines.push(format!("- Checks run: {}", summary.check_count()));
    lines.push(format!("- Passed: {}", summary.passed_count()));
    lines.push(format!("- Failed: {}", summary.failed_count()));
    lines.push(format!("- Warnings: {}", summary.warning_count()));
    lines.push(format!("- Skipped: {}", summary.skipped_count()));
    lines.push(format!(
        "- Commands summarized: {}",
        summary.command_count()
    ));
    lines.push(String::new());

    lines.push("## Check Results".to_string());
    lines.push(String::new());
    lines.push("| Check ID | Status | Message |".to_string());
    lines.push("| --- | --- | --- |".to_string());

    for result in packet.check_results() {
        lines.push(format!(
            "| `{}` | {} | {} |",
            escape_table_cell(result.check_id()),
            escape_table_cell(result.status()),
            escape_table_cell(result.message())
        ));
    }

    lines.push(String::new());
    lines.push("## Command Outcomes".to_string());
    lines.push(String::new());

    if packet.command_summaries().is_empty() {
        lines.push("No command outcomes were captured for this evidence packet.".to_string());
    } else {
        lines.push("| Command | Working Directory | Exit Code | Success | Stdout Summary | Stderr Summary |".to_string());
        lines.push("| --- | --- | --- | --- | --- | --- |".to_string());

        for command in packet.command_summaries() {
            lines.push(render_command_summary_row(command));
        }
    }

    lines.push(String::new());
    lines.push("## Risks and Limitations".to_string());
    lines.push(String::new());

    for risk in packet.risks() {
        lines.push(format!("- {}", risk));
    }

    lines.push(String::new());
    lines.join("\n")
}

/// Writes the latest check evidence packet to the workspace report directory.
pub fn write_check_evidence_packet(
    context: &WorkspaceContext,
    report: &CheckRunReport,
) -> MonadResult<PathBuf> {
    let packet = evidence_packet_from_check_run_report(report);
    let markdown = render_evidence_packet_markdown(&packet);
    let output_path = context.root().join(DEFAULT_EVIDENCE_REPORT_PATH);

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            MonadError::internal(format!(
                "failed to create evidence report directory `{}`: {error}",
                parent.display()
            ))
        })?;
    }

    fs::write(&output_path, markdown).map_err(|error| {
        MonadError::internal(format!(
            "failed to write evidence report `{}`: {error}",
            output_path.display()
        ))
    })?;

    Ok(output_path)
}

fn render_command_summary_row(command: &EvidenceCommandSummary) -> String {
    format!(
        "| `{}` | `{}` | {} | {} | {} | {} |",
        escape_table_cell(command.command()),
        escape_table_cell(command.working_directory()),
        command
            .exit_code()
            .map_or_else(|| "unknown".to_string(), |code| code.to_string()),
        command.success(),
        escape_table_cell(command.stdout_summary().unwrap_or("")),
        escape_table_cell(command.stderr_summary().unwrap_or(""))
    )
}

fn escape_table_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', "<br>")
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    use crate::{CheckId, CheckResult, CheckRunReport, WorkspaceContext};

    use super::*;

    fn unique_temp_root(name: &str) -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|duration| duration.as_nanos())
            .unwrap_or(0);

        std::env::temp_dir().join(format!("monad-{name}-{unique}"))
    }

    #[test]
    fn markdown_report_includes_summary_and_check_results() {
        let report = CheckRunReport::new(
            crate::initial_workspace_check_registry(),
            vec![CheckResult::passed(
                CheckId::new("MONAD-CHECK-0001"),
                "required file exists: monad.toml",
            )],
        );
        let packet = evidence_packet_from_check_run_report(&report);

        let markdown = render_evidence_packet_markdown(&packet);

        assert!(markdown.contains("# Monad check evidence packet"));
        assert!(markdown.contains("## Summary"));
        assert!(markdown.contains("- Result: passed"));
        assert!(markdown.contains("`MONAD-CHECK-0001`"));
        assert!(markdown.contains("required file exists: monad.toml"));
    }

    #[test]
    fn markdown_report_escapes_table_pipes() {
        let report = CheckRunReport::new(
            crate::initial_workspace_check_registry(),
            vec![CheckResult::failed(
                CheckId::new("MONAD-CHECK-PIPE"),
                "value contained a | pipe",
            )],
        );
        let packet = evidence_packet_from_check_run_report(&report);

        let markdown = render_evidence_packet_markdown(&packet);

        assert!(markdown.contains("value contained a \\| pipe"));
    }

    #[test]
    fn write_check_evidence_packet_writes_latest_report() -> MonadResult<()> {
        let root = unique_temp_root("evidence-report");
        fs::create_dir_all(&root).map_err(|error| {
            MonadError::internal(format!("test root should be created: {error}"))
        })?;

        let context = WorkspaceContext::new(&root)?;
        let report = CheckRunReport::new(
            crate::initial_workspace_check_registry(),
            vec![CheckResult::passed(
                CheckId::new("MONAD-CHECK-0001"),
                "required file exists: monad.toml",
            )],
        );

        let path = write_check_evidence_packet(&context, &report)?;
        let content = fs::read_to_string(&path).map_err(|error| {
            MonadError::internal(format!("evidence report should be readable: {error}"))
        })?;

        assert_eq!(path, root.join(DEFAULT_EVIDENCE_REPORT_PATH));
        assert!(content.contains("# Monad check evidence packet"));
        assert!(content.contains("MONAD-CHECK-0001"));

        fs::remove_dir_all(&root).ok();

        Ok(())
    }
}
